os: linux
dist: focal
jobs:
  include: 
  - name: “test123” # existing functionality
    script: # existing functionality
      - java -version
  - name: “sbom”
    language: java
    script: # existing functionality
      - java -version
    addons:
      sbom:
        on:
          branch: 'main'
          pr: false
        # condition: false
        run_phase: "after_success"
        output_format: "cyclonedx-json"
        output_dir: "/test"
        input_dir: "/java"
      deploy:
        provider: releases
        edge: true
        file_glob: true
        file: test/**/*
        skip_cleanup: true
        on:
         branch: main
